// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsxlvwwebbakmzpwjfbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzeGx2d3dlYmJha216cHdqZmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1Nzk5MTEsImV4cCI6MjA2MzE1NTkxMX0.KVICB5llAG7xKB-2ZpskvvF78ekJ0Hkd8ZEHubsi7g8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);